### ISSUE TITLE
Name UG

### ISSUE THREAD

**Issue by maknoll** [Makerburg/makerburg.de#1]
Innovationswerkstatt

**Comment by theandrelf** [comment]
"Innovationswerkstatt" <-- kann ich mit leben, würde es aber noch abstrakter bevorzugen.
Z.B. sowas wie "HKF UG"

Begründung: Im Moment ist unser Focus noch auf Bausteln (also Werkstatt und Dinge herstellen), einen Teil wird aber sicher auch schon Schulung und Beratung ausmachen. Nun kann es ja sein, dass wir in 5 Jahren eigentlich nur noch Beraten wollen und dafür ordentlich für unser Spezialexpertenwissen (Vorträge, Seminare, Firmenberatung, etc.) Kohle verlangen. Dann passt "Werkstatt" vielleicht nicht mehr so.

**Comment by maknoll** [comment]
This issue was moved to Makerburg/Orga#8
