### ISSUE TITLE
Shirts

### ISSUE THREAD

**Issue by maknoll** [Makerburg/makerburg.de#15]
Ich finde ja da "Prison changed me" toll, weiß aber nicht ob Leute den Kontext verstehen.
Auf jeden Fall sollte "Makerburg" drauf. Ich schau mich mal bei den Bedruckern um.

**Comment by maknoll** [comment]
Hier mal der Schriftzug Makerburg in ein paar Fonts

![makerburg_logo](https://cloud.githubusercontent.com/assets/615631/7441212/beaa4556-f0dd-11e4-9cb3-513ee145e6a7.png)

**Comment by maknoll** [comment]
bei spreadshirt ab 18,90 € mit gutem shirt und einseitig bedruckt.

**Comment by theandrelf** [comment]
"Prison changed me" find ich witzig ... aber ja, der Kontext ... für die Zeit in der JVA könnte man das aber machen :)

Zu den Fonts: den letzten nicht

Falls wir ein Logo wollen: da kann man vielleicht auch mal einen Wettbewerb ausschreiben. Der Gewinner und ggfs. auch der 2. und 3. Platz können dann ja Maschinenstunden o.ä. gewinnen.

**Comment by maknoll** [comment]
This issue was moved to Makerburg/Orga#2
