### ISSUE TITLE
Website ist kaputt ;(

### ISSUE THREAD

**Issue by theandrelf** [Makerburg/makerburg.de#17]
Zumindest schmeißt er bei mir gerade ein 404.
Martin hat da zuletzt was geändert. Bitte wieder reparieren. :)

**Comment by maknoll** [comment]
dig www.makerburg.de +nostats +nocomments +nocmd

; <<>> DiG 9.8.3-P1 <<>> www.makerburg.de +nostats +nocomments +nocmd
;; global options: +cmd
;www.makerburg.de.		IN	A
makerburg.de.		300	IN	SOA	ns1.apfohl.com. admin.apfohl.com. 1430739932 86400 7200 604800 300

Garnix is kaputt. Hab die neue Domain eingerichtet. Da die Raketenwissenschaftler vom Decix ne TTL von 24h auf ihren Bullshitrecord gesetzt haben, dauert das noch eine wenig bis das auf die Nameserver durchtrickelt.

**Comment by maknoll** [comment]
Bei mir ist das "Durchtrickeln" übrigens grade passiert. Kann aber sein das euer DNS noch anders ist.
