### ISSUE TITLE
Whiteboard

### ISSUE THREAD

**Issue by maknoll** [Makerburg/makerburg.de#6]

**Comment by Hichi** [comment]
Diese:
http://www.ebay.de/itm/Whiteboard-Wandtafel-Magnettafel-Schreibtafel-Tafel-Memoboard-120-x-90-cm-/251864040665? wurde am 1.05.2015 bestellt. Wird zu Kata geliefert.

**Comment by maknoll** [comment]
Ich mag Neten

**Comment by maknoll** [comment]
This issue was moved to Makerburg/Orga#6
