### ISSUE TITLE
Schraubstock

### ISSUE THREAD

**Issue by maknoll** [Makerburg/makerburg.de#7]

**Comment by theandrelf** [comment]
+ Maschinenschraubstock

**Comment by maknoll** [comment]
in welchem Preisrahmen soll sich der Schraubstock denn bewegen? Bei Ebay gehen die recht teuer weg.
Was sagt ihr zum Beispiel zu dem [hier](http://www.amazon.de/Brockhaus-Heuer-100-Parallel-Schraubstock-8-2057E/dp/B000VCZPR0/ref=sr_1_4?ie=UTF8&qid=1430587718&sr=8-4&keywords=schraubstock+heuer)?

**Comment by maknoll** [comment]
[Der hier](http://www.pollin.de/shop/dt/Nzc2ODk0OTk-/Werkstatt/Werkzeuge/Sonstiges/Tisch_Schraubstock_PTS_1500_mit_Amboss.html) bei Pollin ist herausragend günstig.

Maschinenschraubstöcke gibs günstig bei [Reichelt](http://www.reichelt.de/BS-60429/3/index.html?&ACTION=3&LA=446&ARTICLE=117550&artnr=BS+60429&SEARCH=Maschinenschraubstock).

**Comment by maknoll** [comment]
find ich gut.

**Comment by theandrelf** [comment]
OK, dann schreib ich mal auf die N39-ML ob wer mit bei Pollin bestellen mag.

Den Maschinenschraubstock würde ich gleich bei Eric über die Reicheltsammelbestellung ordern. Falls Eric die Bestellung noch nicht rausgeschickt hat.

**Comment by maknoll** [comment]
This issue was moved to Makerburg/Orga#5
