### ISSUE TITLE
Werbung/sozialeNW

### ISSUE THREAD

**Issue by theandrelf** [Makerburg/makerburg.de#9]
Wenn dann der Name feststeht (e.g. Makerburg), dann

- ~~Twitteraccount~~
- Domain registrieren
- ~~Website ausbauen~~ #10 
- Flyer/Poster basteln

**Comment by maknoll** [comment]
https://twitter.com/makerburg

**Comment by theandrelf** [comment]
Hab wegen Domain schon Andi angemailt. Würde er machen. Er braucht dann aber Name, Adresse und so.
Wäre vermutlich sinnvoll da einen von uns erstmal zu nehmen. Warten bis die Firma existiert finde ich etwas zu lange. Oder?

**Comment by maknoll** [comment]
This issue was moved to Makerburg/Orga#3
